/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppAlquileresRouteImport } from './routes/_app/alquileres'
import { Route as AppAyudaRouteImport } from './routes/_app/ayuda'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppDevolucionesRouteImport } from './routes/_app/devoluciones'
import { Route as AppInventarioRouteImport } from './routes/_app/inventario'
import { Route as AppSeguridadRouteImport } from './routes/_app/seguridad'
import { Route as AppAlquileresIndexRouteImport } from './routes/_app/alquileres.index'
import { Route as AppAlquileresNuevoRouteImport } from './routes/_app/alquileres.nuevo'
import { Route as AppDevolucionesIndexRouteImport } from './routes/_app/devoluciones.index'
import { Route as AppDevolucionesIdRouteImport } from './routes/_app/devoluciones.$id'
import { Route as AppInventarioIndexRouteImport } from './routes/_app/inventario.index'
import { Route as AppInventarioNuevoRouteImport } from './routes/_app/inventario.nuevo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAlquileresRoute = AppAlquileresRouteImport.update({
  id: '/alquileres',
  path: '/alquileres',
  getParentRoute: () => AppRoute,
} as any)
const AppAyudaRoute = AppAyudaRouteImport.update({
  id: '/ayuda',
  path: '/ayuda',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDevolucionesRoute = AppDevolucionesRouteImport.update({
  id: '/devoluciones',
  path: '/devoluciones',
  getParentRoute: () => AppRoute,
} as any)
const AppInventarioRoute = AppInventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => AppRoute,
} as any)
const AppSeguridadRoute = AppSeguridadRouteImport.update({
  id: '/seguridad',
  path: '/seguridad',
  getParentRoute: () => AppRoute,
} as any)
const AppAlquileresIndexRoute = AppAlquileresIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAlquileresRoute,
} as any)
const AppAlquileresNuevoRoute = AppAlquileresNuevoRouteImport.update({
  id: '/nuevo',
  path: '/nuevo',
  getParentRoute: () => AppAlquileresRoute,
} as any)
const AppDevolucionesIndexRoute = AppDevolucionesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDevolucionesRoute,
} as any)
const AppDevolucionesIdRoute = AppDevolucionesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppDevolucionesRoute,
} as any)
const AppInventarioIndexRoute = AppInventarioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppInventarioRoute,
} as any)
const AppInventarioNuevoRoute = AppInventarioNuevoRouteImport.update({
  id: '/nuevo',
  path: '/nuevo',
  getParentRoute: () => AppInventarioRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/alquileres': typeof AppAlquileresRouteWithChildren
  '/ayuda': typeof AppAyudaRoute
  '/dashboard': typeof AppDashboardRoute
  '/devoluciones': typeof AppDevolucionesRouteWithChildren
  '/inventario': typeof AppInventarioRouteWithChildren
  '/seguridad': typeof AppSeguridadRoute
  '/alquileres/nuevo': typeof AppAlquileresNuevoRoute
  '/devoluciones/$id': typeof AppDevolucionesIdRoute
  '/inventario/nuevo': typeof AppInventarioNuevoRoute
  '/alquileres/': typeof AppAlquileresIndexRoute
  '/devoluciones/': typeof AppDevolucionesIndexRoute
  '/inventario/': typeof AppInventarioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ayuda': typeof AppAyudaRoute
  '/dashboard': typeof AppDashboardRoute
  '/seguridad': typeof AppSeguridadRoute
  '/alquileres/nuevo': typeof AppAlquileresNuevoRoute
  '/devoluciones/$id': typeof AppDevolucionesIdRoute
  '/inventario/nuevo': typeof AppInventarioNuevoRoute
  '/alquileres': typeof AppAlquileresIndexRoute
  '/devoluciones': typeof AppDevolucionesIndexRoute
  '/inventario': typeof AppInventarioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/alquileres': typeof AppAlquileresRouteWithChildren
  '/_app/ayuda': typeof AppAyudaRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/devoluciones': typeof AppDevolucionesRouteWithChildren
  '/_app/inventario': typeof AppInventarioRouteWithChildren
  '/_app/seguridad': typeof AppSeguridadRoute
  '/_app/alquileres/nuevo': typeof AppAlquileresNuevoRoute
  '/_app/devoluciones/$id': typeof AppDevolucionesIdRoute
  '/_app/inventario/nuevo': typeof AppInventarioNuevoRoute
  '/_app/alquileres/': typeof AppAlquileresIndexRoute
  '/_app/devoluciones/': typeof AppDevolucionesIndexRoute
  '/_app/inventario/': typeof AppInventarioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/alquileres'
    | '/ayuda'
    | '/dashboard'
    | '/devoluciones'
    | '/inventario'
    | '/seguridad'
    | '/alquileres/nuevo'
    | '/devoluciones/$id'
    | '/inventario/nuevo'
    | '/alquileres/'
    | '/devoluciones/'
    | '/inventario/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/ayuda'
    | '/dashboard'
    | '/seguridad'
    | '/alquileres/nuevo'
    | '/devoluciones/$id'
    | '/inventario/nuevo'
    | '/alquileres'
    | '/devoluciones'
    | '/inventario'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/alquileres'
    | '/_app/ayuda'
    | '/_app/dashboard'
    | '/_app/devoluciones'
    | '/_app/inventario'
    | '/_app/seguridad'
    | '/_app/alquileres/nuevo'
    | '/_app/devoluciones/$id'
    | '/_app/inventario/nuevo'
    | '/_app/alquileres/'
    | '/_app/devoluciones/'
    | '/_app/inventario/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/alquileres': {
      id: '/_app/alquileres'
      path: '/alquileres'
      fullPath: '/alquileres'
      preLoaderRoute: typeof AppAlquileresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ayuda': {
      id: '/_app/ayuda'
      path: '/ayuda'
      fullPath: '/ayuda'
      preLoaderRoute: typeof AppAyudaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/devoluciones': {
      id: '/_app/devoluciones'
      path: '/devoluciones'
      fullPath: '/devoluciones'
      preLoaderRoute: typeof AppDevolucionesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventario': {
      id: '/_app/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof AppInventarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/seguridad': {
      id: '/_app/seguridad'
      path: '/seguridad'
      fullPath: '/seguridad'
      preLoaderRoute: typeof AppSeguridadRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alquileres/': {
      id: '/_app/alquileres/'
      path: '/'
      fullPath: '/alquileres/'
      preLoaderRoute: typeof AppAlquileresIndexRouteImport
      parentRoute: typeof AppAlquileresRoute
    }
    '/_app/alquileres/nuevo': {
      id: '/_app/alquileres/nuevo'
      path: '/nuevo'
      fullPath: '/alquileres/nuevo'
      preLoaderRoute: typeof AppAlquileresNuevoRouteImport
      parentRoute: typeof AppAlquileresRoute
    }
    '/_app/devoluciones/': {
      id: '/_app/devoluciones/'
      path: '/'
      fullPath: '/devoluciones/'
      preLoaderRoute: typeof AppDevolucionesIndexRouteImport
      parentRoute: typeof AppDevolucionesRoute
    }
    '/_app/devoluciones/$id': {
      id: '/_app/devoluciones/$id'
      path: '/$id'
      fullPath: '/devoluciones/$id'
      preLoaderRoute: typeof AppDevolucionesIdRouteImport
      parentRoute: typeof AppDevolucionesRoute
    }
    '/_app/inventario/': {
      id: '/_app/inventario/'
      path: '/'
      fullPath: '/inventario/'
      preLoaderRoute: typeof AppInventarioIndexRouteImport
      parentRoute: typeof AppInventarioRoute
    }
    '/_app/inventario/nuevo': {
      id: '/_app/inventario/nuevo'
      path: '/nuevo'
      fullPath: '/inventario/nuevo'
      preLoaderRoute: typeof AppInventarioNuevoRouteImport
      parentRoute: typeof AppInventarioRoute
    }
  }
}

interface AppAlquileresRouteChildren {
  AppAlquileresNuevoRoute: typeof AppAlquileresNuevoRoute
  AppAlquileresIndexRoute: typeof AppAlquileresIndexRoute
}

const AppAlquileresRouteChildren: AppAlquileresRouteChildren = {
  AppAlquileresNuevoRoute: AppAlquileresNuevoRoute,
  AppAlquileresIndexRoute: AppAlquileresIndexRoute,
}

const AppAlquileresRouteWithChildren = AppAlquileresRoute._addFileChildren(
  AppAlquileresRouteChildren,
)

interface AppDevolucionesRouteChildren {
  AppDevolucionesIdRoute: typeof AppDevolucionesIdRoute
  AppDevolucionesIndexRoute: typeof AppDevolucionesIndexRoute
}

const AppDevolucionesRouteChildren: AppDevolucionesRouteChildren = {
  AppDevolucionesIdRoute: AppDevolucionesIdRoute,
  AppDevolucionesIndexRoute: AppDevolucionesIndexRoute,
}

const AppDevolucionesRouteWithChildren = AppDevolucionesRoute._addFileChildren(
  AppDevolucionesRouteChildren,
)

interface AppInventarioRouteChildren {
  AppInventarioNuevoRoute: typeof AppInventarioNuevoRoute
  AppInventarioIndexRoute: typeof AppInventarioIndexRoute
}

const AppInventarioRouteChildren: AppInventarioRouteChildren = {
  AppInventarioNuevoRoute: AppInventarioNuevoRoute,
  AppInventarioIndexRoute: AppInventarioIndexRoute,
}

const AppInventarioRouteWithChildren = AppInventarioRoute._addFileChildren(
  AppInventarioRouteChildren,
)

interface AppRouteChildren {
  AppAlquileresRoute: typeof AppAlquileresRouteWithChildren
  AppAyudaRoute: typeof AppAyudaRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDevolucionesRoute: typeof AppDevolucionesRouteWithChildren
  AppInventarioRoute: typeof AppInventarioRouteWithChildren
  AppSeguridadRoute: typeof AppSeguridadRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlquileresRoute: AppAlquileresRouteWithChildren,
  AppAyudaRoute: AppAyudaRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDevolucionesRoute: AppDevolucionesRouteWithChildren,
  AppInventarioRoute: AppInventarioRouteWithChildren,
  AppSeguridadRoute: AppSeguridadRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
